#! /bin/bash
# Licensed under the GNU General Public License Version 2
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
####################################################################################################
## Authored by Anthony Nordquist. https://github.com/SalineOS salinelinux@gmail.com 
## Copyright 2013 Anthony Nordquist

Input="$@"

Suffix=$(echo "$Input" | awk -F '.' '{print $NF}')

if [ "$Suffix" = "mp3" ]; then
 Lyrics=$(echo "$Input" | basename "$Input" $Suffix)
elif [ "$Suffix" = "flac" ]; then
 Lyrics=$(echo "$Input" | basename "$Input" $Suffix)
elif [ "$Suffix" = "aac" ]; then
 Lyrics=$(echo "$Input" | basename "$Input" $Suffix)
elif [ "$Suffix" = "mp4" ]; then
 Lyrics=$(echo "$Input" | basename "$Input" $Suffix)
elif [ "$Suffix" = "mkv" ]; then
 Lyrics=$(echo "$Input" | basename "$Input" $Suffix)
elif [ "$Suffix" = "wmp" ]; then
 Lyrics=$(echo "$Input" | basename "$Input" $Suffix)
elif [ "$Suffix" = "ogg" ]; then
 Lyrics=$(echo "$Input" | basename "$Input" $Suffix)
fi

Lyrics=$(echo "$Input" | sed -e "s|(||g" | sed -e "s|)||g" | sed -e "s|-||g" | sed -e "s|[0-9]||g" | sed -e "s|_||g" | sed -e "s|~||g" | sed -e "s|\.||g" | sed -e "s|,||g" | sed -e "s|\[||g" | sed -e "s|\]||g" | sed -e "s|\}||g" | sed -e "s|%||g" | sed -e "s|@||g" | sed -e "s|#||g")

exec /usr/bin/search-all-the-things-Lyrics "$Lyrics" &

exit